### ISSUE TITLE
Cursor is not visible when using toggleterm.nvim

### ISSUE THREAD

**Issue by oxfist** [oxfist/night-owl.nvim#15]
Plugin https://github.com/akinsho/toggleterm.nvim

The cursor is not visible after `f`
<img width="1574" alt="Screenshot 2023-06-29 at 3 17 18 PM" src="https://github.com/oxfist/night-owl.nvim/assets/132054595/195a67df-8992-4c72-adf9-9d74b517013d">

_Originally posted by @kmlopez-hhl in https://github.com/oxfist/night-owl.nvim/issues/2#issuecomment-1612540276_

**Comment by oxfist** [comment]
@kmlopez-hhl I just added the correct colors for those highlight groups, it should be fixed now!

**Comment by oxfist** [comment]
@all-contributors please add @kmlopez-hhl for bug.

**Comment by kmlopez-hhl** [comment]
Thanks @oxfist, awesome work! Okay, time to change tokyonight back to your night owl plugin !
