### ISSUE TITLE
When loading this theme with lazy.nvim, visual selection stops working when unfocusing and focusing back to neovim

### ISSUE THREAD

**Issue by lampewebdev** [oxfist/night-owl.nvim#2]
Hej,

I'm loading your theme with lazy.

When I have this theme loaded the first selection works in visual mode.

When I then un focus the window the selection is gone and selecting new text is not visible.

https://github.com/oxfist/night-owl.nvim/assets/44268468/92a0ed33-00bc-4558-ad52-59672d62849a

**Comment by oxfist** [comment]
@lampewebdev Thanks for reporting this issue and for providing a video! 🎉

Not quite sure what's causing this, although I have a sense on what the issue could be. This plugin creates a couple `autocmd`s to change the `Visual` highlight group on `FocusGained` and on `FocusLost`:

```lua
vim.api.nvim_create_autocmd({ "FocusGained" }, {
	pattern = "*",
	command = "hi! link Visual VisualActive",
})

vim.api.nvim_create_autocmd({ "FocusLost" }, {
	pattern = "*",
	command = "hi! link Visual VisualInactive",
})
```

Based on what you're showing I think either something is going on with those events or something else is also changing those highlight groups.

To help debug this further can you please share the following details? I'd love to fix this for you.

1. Which Neovim version are you running?
2. Do you have any plugins installed that might be setting the `Visual` highlight group by any chance?
3. Do you have any plugins installed that might also be creating `autocmd`s on `FocusGained` or on `FocusLost`?
4. What do you get when running `:verbose hi Visual`, `:verbose hi VisualActive`, and `:verbose hi VisualInactive` _before_ unfocusing your terminal?
5. What do you get when running `:verbose hi Visual`, `:verbose hi VisualActive`, and `:verbose hi VisualInactive` _after_ unfocusing your terminal?

**Comment by oxfist** [comment]
@lampewebdev also, do you get the same issue if you disable all other themes and just enable this one?

**Comment by lampewebdev** [comment]
- Which Neovim version are you running?
0.9.1
- Do you have any plugins installed that might be setting the Visual highlight group by any chance?
Treesiter. besides that I'm not sure.
- Do you have any plugins installed that might also be creating autocmds on FocusGained or on FocusLost?
How can i check that?
- What do you get when running :verbose hi Visual, :verbose hi VisualActive, and :verbose hi VisualInactive before unfocusing your terminal?
```
:verbose hi Visual                                                                                                                                                                                                                                
Visual         xxx ctermfg=234 ctermbg=109 guifg=#1c1c1c guibg=#87afaf                                                                                                                                                                             
                   links to VisualActive                                                                                                                                                                                                           
        Last set from Lua    

:verbose hi VisualActive                                                                                                                                                                                                                          
VisualActive   xxx cleared 

:verbose hi VisualInactive                                                                                                                                                                                                                        
VisualInactive xxx cleared
```
   
- What do you get when running :verbose hi Visual, :verbose hi VisualActive, and :verbose hi VisualInactive after unfocusing your terminal?
It shows the same

- do you get the same issue if you disable all other themes and just enable this one?
yes

**Comment by lampewebdev** [comment]
Just some things I tried:
- setting a new color theme fixes this until i unfocus again
- :set background=dark also fixes the problem until unfocus
- If I disable all other plugins beside this one it still does not work

**Comment by lampewebdev** [comment]
Okay I have repro I think.
1. Add your theme and telescope.
2. Use the following telescope config
```
local builtin = require('telescope.builtin')
local telescope = require('telescope')
local actions = require('telescope.actions')

local grep_args = { '--hidden', '--glob', '!**/.git/*' }

telescope.setup({
    defaults = {
        path_display = { "truncate" },
        layout_strategy = 'horizontal',
        layout_config = {
            height = vim.o.lines,
            width = vim.o.columns,
            horizontal = {
                prompt_position = "bottom",
                preview_width = 0.7,
                -- results_width = 0.8,
            },
            vertical = {
                mirror = false,
            },
        },
        mappings = {
            i = {
                ['<esc>'] = actions.close
            },
        },
    },
    pickers = {
        find_files = {
            find_command = { 'fd', '--type', 'f', '--hidden', '--exclude', '.git' }
        },
        live_grep = {
            additional_args = function(opts)
                return grep_args
            end
        },
        grep_string = {
            additional_args = function(opts)
                return grep_args
            end
        },
    },
})

vim.keymap.set('n', '<leader>tf', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>tg', builtin.git_files, { desc = "Telescope git files" })
vim.keymap.set('n', '<leader>tl', builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set('n', '<leader>ts', builtin.grep_string, { desc = "Telescope grep string" })
vim.keymap.set('n', '<leader>tb', builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set('n', '<leader>tc', builtin.commands, { desc = "Telescope commands" })
vim.keymap.set('n', '<leader>tk', builtin.keymaps, { desc = "Telescope keymaps" })
vim.keymap.set('n', '<leader>th', builtin.git_bcommits, { desc = "Telescope file git history" })
vim.keymap.set('n', '<leader>tr', builtin.lsp_references, { desc = "Telescope find references" })
vim.keymap.set('n', '<leader>td', builtin.diagnostics, { desc = "Telescope find diagnostics" })
```

**Comment by lampewebdev** [comment]
I'm pretty sure that this is the problem here https://github.com/oxfist/night-owl.nvim/blob/a6d84aa32b3708bc32397aa86b26317441bbd1d5/after/plugin/autocmds.lua#L3

Not sure how neovim works here but this code should only run when the night owl theme is active and set this back to the default option once the theme is changed.

**Comment by oxfist** [comment]
@lampewebdev thanks so much for your updates. I'll be able to dive into this this week and should have an update for you soon.

Just FYI, you can check the autocommands currently defined by running `:autocmd FocusGained` and `:autocmd FocusLost`. For me it shows this: 

```
FocusGained
    *         hi! link Visual VisualActive
```
But I think you're on the right path, the autocommand shouldn't be set if the theme is not active. So I'll try to reproduce this and work on a fix.

**Comment by lampewebdev** [comment]
I only see this

```
:autocmd FocusGained                                                                                                     
--- Autocommands ---                                                                                                     
FocusGained                                                                                                              
    *         hi! link Visual VisualActive                                                                               
Press ENTER or type command to continue  
```

```
:autocmd FocusLost                                                                                                       
--- Autocommands ---                                                                                                     
FocusLost                                                                                                                
    *         hi! link Visual VisualInactive                                                                             
Press ENTER or type command to continue   
```

**Comment by kmlopez-hhl** [comment]
It's also messing up Lunar Vim's toggle term config, the cursor is not visible.

**Comment by oxfist** [comment]
@kmlopez-hhl I'm not very familiar with LunarVim, can you show me how that looks like? I'm trying to fix this and want to make sure the solution will include your setup or create a separate issue to track that separately. 🙏🏼

**Comment by denisw** [comment]
I'm experiencing that problem as well. Having the package loaded (Packer `use`) seems to be enough for this problem to happen.

**Comment by denisw** [comment]
@oxfist I think the issue is that the `autocmd` commands are in the `after/` directory, which according to the Neovim docs are run when the plugin is loaded, not when the colorscheme is activated. 

Perhaps you can use the `ColorScheme` autocmd to detect when the `night-owl` colorscheme gets (de)activated and use that to (un)register the `FocusGained` / `FocusLost` autocmds?

**Comment by oxfist** [comment]
@denisw @lampewebdev @kmlopez-hhl I was able to set the `FocusGained` and `FocusLost` highlight groups only when colorscheme is `night-owl`. Tested this on a minimal `lazy.nvim` config on my local environment and can confirm it works as expected ONLY when this theme is loaded.

 Please let me know if you still have any issues! 🙏🏼

**Comment by oxfist** [comment]
@all-contributors
please add @lampewebdev for bug
please add @denisw for bug

**Comment by oxfist** [comment]
@all-contributors please add @denisw for bug

**Comment by oxfist** [comment]
@all-contributors
please add @lampewebdev for bug.
please add @denisw for bug.

**Comment by oxfist** [comment]
@all-contributors
please add @denisw for bug.
please add @lampewebdev 	for bug.

**Comment by oxfist** [comment]
@all-contributors please add @denisw for bug

**Comment by kmlopez-hhl** [comment]
@oxfist thank you!

I just installed the latest, but it is still happening.

The cursor is not visible after `f`
<img width="1574" alt="Screenshot 2023-06-29 at 3 17 18 PM" src="https://github.com/oxfist/night-owl.nvim/assets/132054595/195a67df-8992-4c72-adf9-9d74b517013d">

**Comment by oxfist** [comment]
@kmlopez-hhl thanks so much for the follow-up, I created a separate issue to track that. I haven't installed `toggleterm` on my local environment yet but I'll reproduce the issue so I can fix it and support that plugin too.

**Comment by DevanB** [comment]
@oxfist I hate to possibly open up an old issue. However, I think this issue is occurring again. I don't mind opening another issue, but figured for historical purposes I'd add it here initially. I'm able to replicate the issue by using the basic [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua) (a lovely starter point from T.J.!) and replacing the color scheme block with:

```lua
{
  'oxfist/night-owl.nvim',
  lazy = false,
  priority = 1000,
  config = function()
    vim.cmd.colorscheme 'night-owl'
  end,
},
```

And here is the answers the questions you've asked previously:

- Which Neovim version are you running?
`0.9.1`

- Do you have any plugins installed that might be setting the Visual highlight group by any chance?
I don't understand enough about Visual highlight groups to know if any of the standard plugins within kickstart.nvim do this. I'm sorry.

- Do you have any plugins installed that might also be creating autocmds on FocusGained or on FocusLost?
Unfortunately, I have the same answer as the previous question. I don't know enough to confidently answer this question.

- What do you get when running `:verbose hi Visual`, `:verbose hi VisualActive`, and `:verbose hi VisualInactive` before unfocusing your terminal?

<details>
<summary>Visual</summary>

```
:verbose hi Visual                                                                                                                     
Visual         xxx links to VisualActive                                                                                               
        Last set from Lua  
```

</details>

<details>
<summary>VisualActive</summary>

```
:verbose hi VisualActive                                                                                                               
VisualActive   xxx guibg=#1d3b53                                                                                                       
        Last set from Lua  
```

</details>

<details>
<summary>VisualInactive</summary>

```
:verbose hi VisualInactive                                                                                                             
VisualInactive xxx guibg=#2e2d5e                                                                                                       
        Last set from Lua 
```

</details>

- What do you get when running `:verbose hi Visual`, `:verbose hi VisualActive`, and `:verbose hi VisualInactive` after unfocusing your terminal?

<details>
<summary>Visual</summary>

```
:verbose hi Visual                                                                                                                     
Visual         xxx links to @nowl.visual.active                                                                                        
        Last set from Lua  
```

</details>

<details>
<summary>VisualActive</summary>

```
:verbose hi VisualActive                                                                                                               
VisualActive   xxx guibg=#1d3b53                                                                                                       
        Last set from Lua 
```

</details>

<details>
<summary>VisualInactive</summary>

```
:verbose hi VisualInactive                                                                                                             
VisualInactive xxx guibg=#2e2d5e                                                                                                       
        Last set from Lua
```

</details>

**Comment by rabiescow** [comment]
I had this when running `:verbose hi Visual`

`Visual         xxx guibg=#282828
                   links to @nowl.visual.active
        Last set from ~/.local/share/nvim/lazy/night-owl.nvim/after/plugin/autocmds.lua
 (run Nvim with -V1 for more details)`

I did a dirty fix added in my **_lazy.lua_** to fix this as **_@nowl.visual.active_** wasn't set.

`:verbose hi "@nowl.visual.active"`
`E411: Highlight group not found: @nowl.visual.active`

**_The fix that worked for me:_**
`vim.api.nvim_set_hl(0, "@nowl.visual.active", { bg = "#343434" })`
