### ISSUE TITLE
[Comment] Treesitter queries

### ISSUE THREAD

**Issue by olimorris** [oxfist/night-owl.nvim#22]
Firstly, congrats on the theme, it's beautiful and I've been a big fan of the original.

I created [onedarkpro.nvim](https://github.com/olimorris/onedarkpro.nvim) and implemented some custom Treesitter queries very similar to yourself.

Just wanted to offer some advice; it's been very helpful for me to prefix my custom queries with "@odp" like I've done [here](https://github.com/olimorris/onedarkpro.nvim/blob/main/after/queries/typescript/highlights.scm). It makes it super easy for people to understand the origin of where the query has come from when they run `:Inspect`. It also stops any collisions between your theme and any other themes that are installed.

**Comment by oxfist** [comment]
Hi @olimorris, thanks so much! This is actually a great idea, I think the amount of custom queries I have is still pretty manageable so I'll explore this change in the upcoming days.
