### ISSUE TITLE
Cursor highlight text contrast color

### ISSUE THREAD

**Issue by StraightOuttaCrompton** [oxfist/night-owl.nvim#29]
The color of the highlighted text has an extremely low contrast

<img width="481" alt="Screenshot 2023-11-18 at 18 42 31" src="https://github.com/oxfist/night-owl.nvim/assets/16123253/c00dd77a-b723-4286-9e93-789cb7c0c2a7">

You can see above the letter `n` is not very visible due to the low contrast.

It would be great if we could change the text color to a dark colour, increasing the contrast and making it more readable.

I would try to make the change myself, but I have only just started out with nvim and I am not sure what would need changing!

**Comment by oxfist** [comment]
@StraightOuttaCrompton Thank you for reporting this! I made some changes to highlight groups recently and I probably messed up something.

I'll take a look and fix it, and then I'll update this thread with some details that could help you get started if you're interested in learning some more about it. 👍🏼

**Comment by oxfist** [comment]
@StraightOuttaCrompton I wasn't able to reproduce this, can you help me by providing the following information:

1. What terminal are you using?
2. Do you have any transparency/contrast option set on it? It seems from the image you shared you have transparency on

For reference, this is what I see:
![CleanShot 2023-11-19 at 6  33 38@2x](https://github.com/oxfist/night-owl.nvim/assets/934679/11fdbdd1-8956-4ea9-b6f1-04182c671c6c)

**Comment by oxfist** [comment]
@StraightOuttaCrompton I updated the `Cursor` related highlight groups but can't really test it on my environment as from what I've read macOS terminals seem to override the cursor color on Neovim 🤷🏼‍♂️ 

Could you update the plugin and test it?

**Comment by StraightOuttaCrompton** [comment]
Thank you for responding so quickly!

> 1. What terminal are you using?

 iTerm2. 

> Do you have any transparency/contrast option set on it? It seems from the image you shared you have transparency on

Yes, I have the following set

```
vim.api.nvim_set_hl(0, "Normal", { bg = "None" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "None" })
```

So I tested in wezterm and it isn't an issue there. Looking around the iterm settings you can set the "Cursor colors" under `Profiles > Colors` which is a good enough fix for me, so I will close the issue 🙏

**Comment by oxfist** [comment]
@StraightOuttaCrompton I'm glad you found a fix! You might already know this if you manually set `Normal` and `NormalFloat` backgrond to `NONE`, but that effectively removes the background color set by this theme, which will result in Neovim having the same exact background color you have set up for your terminal.
