### ISSUE TITLE
TabLine, TabLineSel, and TabLineFill are not set

### ISSUE THREAD

**Issue by zshuzh** [oxfist/night-owl.nvim#3]
When creating tabs in neovim (`:tabnew`) the resulting tab bar does not match the color scheme. I was able to fix this by setting the relevant highlight groups as follows:

```lua
-- ~/.config/nvim/after/plugin/color.lua
vim.cmd.colorscheme('night-owl')

local c = require('night-owl.palette')
local hl = vim.api.nvim_set_hl

hl(0, "TabLine", { fg = c.fg, bg = c.dark2 })
hl(0, "TabLineSel", { fg = 'none', bg = c.blue3 })
hl(0, "TabLineFill", { fg = 'none', bg = c.bg })
```

I'm not sure if these are the _exact_ colors used in the VSCode tabs, but they seem close enough.

**Comment by oxfist** [comment]
@nanyaDev Thanks so much for reporting this! I was able to match VSCode colors and now it looks like this:
<img width="364" alt="image" src="https://github.com/oxfist/night-owl.nvim/assets/934679/c689660f-7c41-494c-be16-d256d8ede695">

**Comment by oxfist** [comment]
@all-contributors please add @nanyaDev for bug
