### ISSUE TITLE
Night-Owl Theme Customization Issue

### ISSUE THREAD

**Issue by gokayburuc** [oxfist/night-owl.nvim#32]
# High-customization optionslike **material.nvim**

I am using night-owl theme but i couldn't find a manual or a wiki to customize theme options just like the other themes such as material.nvim Here is my sample customization file  for material.nvim  i also need something like that for night-owl.nvim. 

thanks in advance for your understanding.

```lua 
require("material").setup({
	contrast = {
		terminal = true,
		sidebars = false,
		cursor_line = true,
		floating_windows = true,
		non_current_windows = false,
		filetypes = {},
	},
	styles = {
		comments = { italic = true },
		strings = { italic = true },
		keywords = { bold = true },
		functions = { bold = true },
		variables = { bold = true },
		operators = { bold = true },
		types = {},
	},
	plugins = {},
	disable = {
		colored_cursor = false,
		borders = false,
		background = false,
		term_colors = false,
		eob_lines = false,
	},
	high_visibility = {
		lighter = false,
		darker = true,
	},
	lualine_style = "default",
	custom_colors = nil,
	custom_highlights = {},
	async_loading = true,
})

```

**Comment by diip3sh** [comment]
Is there any updates on this issue?
I just want to know transparent background is available

**Comment by gokayburuc** [comment]
> Is there any updates on this issue? I just want to know transparent background is available

you can make this manually : 

```lua 
function ColorMe(color)
	color = color or "night-owl"
	vim.o.background = "dark"
	vim.cmd.colorscheme(color)

	TRANSPARENT BACKGROUND
	vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
	vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
end

ColorMe()


```

**Comment by oxfist** [comment]
@gokayburuc @pilladipesh33 sorry for the delay! Thank you for posting on this issue, I definitely want to allow user configurations so I'm starting from https://github.com/oxfist/night-owl.nvim/pull/31 to implement that and allow better options in general. I'll have that implemented in the upcoming days 🙌🏼

**Comment by oxfist** [comment]
@gokayburuc @pilladipesh33 starting from #35, this plugin now allows customizing settings. Feel free to create a separate issue if you have ideas on how to customize this further.

**Comment by oxfist** [comment]
@all-contributors please add @gokayburuc for ideas

**Comment by oxfist** [comment]
@pilladipesh33 Starting from c4eeaf84404eefb07e7bee14252c69d74c7e4206, you can enable transparent background by doing:

```lua
require('night-owl').setup({
	transparent_background = true,
})
```
