### ISSUE TITLE
Opts table is not effective

### ISSUE THREAD

**Issue by andrewberty** [oxfist/night-owl.nvim#42]
### I'm trying to pass opts table to the setup function but it doesn't seem to be effective

**Example config:
Trying to disable italics and enabling transparent background.**

![VtIbL2nFeb](https://github.com/oxfist/night-owl.nvim/assets/95014217/a3f5bee4-2aca-4884-802d-2750f1399cdc)

**Comment by andrewberty** [comment]
Just took a look at the source code, and here's what I noticed

at `theme.lua` file:

tried to inspect the value of `settings.italics` for example

![wezterm-gui_c55BaW6Epz](https://github.com/oxfist/night-owl.nvim/assets/95014217/249d6e46-ba2e-45a9-9c21-9c00aaef9e3c)

It initially reads my custom value which is `false` then immediately it is been set to `true` which I guess is the default

![wezterm-gui_qQ2COpalLG](https://github.com/oxfist/night-owl.nvim/assets/95014217/29a11b26-dc19-4adf-9003-570d8a821ca4)


I'm suspecting that this line might be responsible for calling the setup function with an empty table which will always set the defaults values again.

![wezterm-gui_wwi71Rahgd](https://github.com/oxfist/night-owl.nvim/assets/95014217/d4428398-930c-4d8e-99d8-10c80aabb5d4)

**Comment by oxfist** [comment]
@andrew-george Thanks so much for reporting this. I'll take a look and make sure the setup function works as expected.

**Comment by oxfist** [comment]
@andrew-george are you by any chance setting the `colorscheme` somewhere else in your config?

**Comment by andrewberty** [comment]
@oxfist Sorry for the late reply.

I use lazy so I usually install and configure colorschemes in lazy table and apply it using `vim.cmd` in another separate file

![Screenshot 2024-04-22 154837](https://github.com/oxfist/night-owl.nvim/assets/95014217/f002512a-e325-4566-a154-3aaf7bc546d2)

**Comment by oxfist** [comment]
Hi @andrew-george, I just pushed some changes that should get this fixed. I tried it with a minimal lazy config and got the expected result, i.e. if settings `italics = false` in the `setup` call, then it disables de italics correctly. Could you please test this on your end?

**Comment by andrewberty** [comment]
Thank you for your fast response and fix. It's now indeed working flawlessly.

**Comment by oxfist** [comment]
@all-contributors please add @andrew-george for bug
