### ISSUE TITLE
Color of the Cursor Column (:set cuc / nocuc) does not match the cursor line (:set cul / nocul)

### ISSUE THREAD

**Issue by ProHaller** [oxfist/night-owl.nvim#49]
Would it be possible to change the color of the cursor column to match the discreet highlight of the cursor line?

![CleanShot 2024-08-06 at 15 51 12@2x](https://github.com/user-attachments/assets/bbe8fd68-34ad-4654-9a15-c7bd342edbfa)

**Comment by oxfist** [comment]
@ProHaller thanks for reporting this! I just pushed a fix to match `CursorLine`.

Not really loving how it looks, maybe it's too subtle, but for now it's good enough. I might add a configuration to tweak the colors for both `CursorLine` and `CursorColumn` in the future.

![CleanShot 2024-08-06 at 5  56 40@2x](https://github.com/user-attachments/assets/cd016d01-1040-4e66-a962-c7129a458bb4)

Also, love to see how real Rust code looks like with this theme. If you find any issues with it, please don't hesitate to open a new issue! Thanks again 🙌🏼

**Comment by oxfist** [comment]
@all-contributors please add @ProHaller for bug

**Comment by ProHaller** [comment]
> @ProHaller thanks for reporting this! I just pushed a fix to match `CursorLine`.

You're much welcome! Thank you for the reactivity.

> Not really loving how it looks, maybe it's too subtle, but for now it's good enough. I might add a configuration to tweak the colors for both `CursorLine` and `CursorColumn` in the future.

I agree with that, the contrast is not enough on some monitors to be visible. Maybe a purer black? 

> Also, love to see how real Rust code looks like with this theme. If you find any issues with it, please don't hesitate to open a new issue! Thanks again 🙌🏼

Awesome is how it looks! Thanks for the good work!
