### ISSUE TITLE
Neovide (Neovim GUI) Terminal Colors are not right

### ISSUE THREAD

**Issue by ProHaller** [oxfist/night-owl.nvim#51]
**Issue: Theme Colors Not Applied in Terminal on Neovide**

I'm encountering an issue where the color theme is not properly applied when using a terminal or terminal-like plugins (e.g., LazyGit) within a GUI, specifically Neovide.

### Steps to Reproduce:
1. Install [Neovide](https://github.com/neovide/neovide).
2. Set your color theme to NightOwl in neovim.
3. Open Neovide.
4. Use `:term` to open an embedded terminal.

### Expected Behavior:
The terminal should display colors that match the selected theme (NightOwl in this case).

### Actual Behavior:
The terminal colors do not match the selected theme, leading to inconsistencies between the terminal in Neovide and other terminals like Kitty.

### Additional Information:
- **OS:** macOS Sonoma
- **Terminal:** Kitty
- **Neovim Configuration:** I'm using the NightOwl theme, which works as expected in standard Neovim and Kitty but not in Neovide.
  
It was suggested by a Neovide maintainer that this might be a theme issue. This could be related to the optional colors not being properly set from `g:terminal_color_0` to `g:terminal_color_15`, as mentioned in the [Neovim Manual](https://neovim.io/doc/user/nvim_terminal_emulator.html#terminal-config).

### Screenshots:
Here are some visual comparisons between the different terminals:

- **Kitty:**
  ![Kitty](https://github.com/user-attachments/assets/49546a51-bde8-4889-8b67-18f4c005737d)

- **Neovide:**
  ![Neovide](https://github.com/user-attachments/assets/e6fe3bc9-73db-41fd-b8e2-5cde4b832b9f)

- **Neovim:**
  ![Nvim](https://github.com/user-attachments/assets/bdc5ac1d-17a5-4b30-9fe1-fcac11c10b32)

Is there a way to ensure that the theme colors are correctly applied in Neovide's terminal?

Thank you for your time and assistance.

**Comment by ProHaller** [comment]
Anybody to get an eye on this issue, or to guide me on how to fix it myself?

**Comment by oxfist** [comment]
@ProHaller thanks for creating this issue! Seems like it's definitely on me, as I haven't really defined any of the `g:terminal_color_x` colors nor validated the theme on a GUI-based Neovim.

Just to make sure I understand the context correctly, could you add the steps to reproduce this on Neovide? 🙏🏼

**Comment by ProHaller** [comment]
Thank you very much for taking the time to look up this issue.

I edited my original message to be a little more explicit, tell me if I can do anything more. 

Ps: I did the test with another GUI ([Goneovim](https://github.com/akiyosi/goneovim)) to check and I find the same the same issue: the theme is only applied in the main interface, the terminal ignores it.

**Comment by oxfist** [comment]
Closed by #52
